<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Receiver_linux_wayland-0858644e-c714-4350-8e0c-4589838a99af</UserSecretsId>
        <RootNamespace>Receiver_linux_wayland</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CliWrap" Version="3.9.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="9.0.0" />
    </ItemGroup>
</Project>
